version: '3.8'

services:
  microservicio8:
    image: microservicio8:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8102:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql8

  mysql8:
    image: mysql:8.0
    ports:
      - "3318:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P4ssword!
      MYSQL_DATABASE: my-app